apiVersion: v1            
kind: ConfigMap            
metadata:                               
  name: inventory-config
  namespace: mini-tdmc-control-plane                                                                
data:                                  
  SPRING_PROFILES_ACTIVE: "kubernetes"                                                              
  SERVER_PORT: "4001"
  SPRING_AUTOCONFIGURE_EXCLUDE: "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration"