apiVersion: v1                                                                                      
kind: Namespace                                                                  
metadata:                                                                                           
  name: mini-tdmc-control-plane                                                                   
---                                                                                                 
apiVersion: v1                                                                   
kind: Namespace                                                                                     
metadata:                                                                                           
  name: mini-tdmc-data-plane                                                                        
