apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: inventory-service-monitor
  namespace: mini-tdmc-control-plane
  labels:
    app: inventory-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mini-tdmc-inventory
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
